# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2396e27c175dd88d1ed6018b8948bdad2688eb9b416e632f186c812eba21967b9a60d2d07f04482f24f1b37dccf1e0cc7a127f68aae7f1cb971d4c51c202f7e9

test:
  secret_key_base: 90dfa310437bfa53723fef97e92e7014f87d5aa1d07d5bc19fbdee9fa8de0012c4c2ceead5b50dc515ae225c4ea87968f0348300c85e33eed6e12116a7447728

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
